service: example

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: ap-northeast-1

plugins:
  localPath: '../../'
  modules:
    - serverless-idobata-webhook

custom:
  serverless-idobata-webhook:
    webhookUrl: https://idobata.io/hook/custom/...

functions:
  hello:
    handler: handler.hello
